apiVersion: v1
kind: Namespace
metadata:
  name: test
---
apiVersion: v1
kind: Namespace
metadata:
  name: tools
---
apiVersion: v1
kind: Namespace
metadata:
  name: bryxx-demo
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring