apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 6.57.4
    chart: grafana
    helm:
      parameters:
      - name: adminPassword
        value: "admin123"
      - name: persistence.enabled
        value: "true"
      - name: persistence.storageClassName
        value: "standard"
      - name: persistence.size
        value: "5Gi"
      - name: ingress.enabled
        value: "true"
      - name: ingress.annotations."kubernetes.io/ingress.class"
        value: "nginx" # ✅ Correcte manier om de annotation als string te geven
      - name: ingress.hosts[0]
        value: "grafana.local"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true