apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 6.57.4
    chart: grafana
    helm:
      values: |
        persistence:
          enabled: true
          storageClassName: standard
          size: 5Gi
        adminPassword: admin123
        ingress:
          enabled: true
          annotations:
            kubernetes.io/ingress.class: "nginx"
          hosts:
            - "grafana.local"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true