apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 25.8.0 # Specifieke versie van Prometheus
    chart: prometheus
    helm:
      parameters:
      - name: alertmanager.enabled
        value: "true"
      - name: server.ingress.enabled
        value: "true"
      - name: server.ingress.annotations.kubernetes\\.io/ingress\\.class
        value: "nginx"
      - name: server.ingress.hosts[0]
        value: "prometheus.local"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true